// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvAz-JCPEL9AGmPMA8t5Pe-H3-2GD2VTI',
    appId: '1:419434734005:android:06820488d5aecfada5f9fc',
    messagingSenderId: '419434734005',
    projectId: 'blood-bank-39c73',
    storageBucket: 'blood-bank-39c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCs7loMI-Jw6eJat7RteMSBakEmpVcvCA',
    appId: '1:419434734005:ios:9480b6ebf0329796a5f9fc',
    messagingSenderId: '419434734005',
    projectId: 'blood-bank-39c73',
    storageBucket: 'blood-bank-39c73.firebasestorage.app',
    iosClientId: '419434734005-0ee4lb2dtrod3071kd6hrphlch61a3qa.apps.googleusercontent.com',
    iosBundleId: 'com.octalogicx.bloodbankproject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHTqqK9mQR2XpYRjcbHrEK80jmmRupT8',
    appId: '1:419434734005:web:e0488537ac1edbf0a5f9fc',
    messagingSenderId: '419434734005',
    projectId: 'blood-bank-39c73',
    authDomain: 'blood-bank-39c73.firebaseapp.com',
    storageBucket: 'blood-bank-39c73.firebasestorage.app',
    measurementId: 'G-F2BTMHWWBX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCs7loMI-Jw6eJat7RteMSBakEmpVcvCA',
    appId: '1:419434734005:ios:9480b6ebf0329796a5f9fc',
    messagingSenderId: '419434734005',
    projectId: 'blood-bank-39c73',
    storageBucket: 'blood-bank-39c73.firebasestorage.app',
    iosClientId: '419434734005-0ee4lb2dtrod3071kd6hrphlch61a3qa.apps.googleusercontent.com',
    iosBundleId: 'com.octalogicx.bloodbankproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHTqqK9mQR2XpYRjcbHrEK80jmmRupT8',
    appId: '1:419434734005:web:cc6d971faf0c5955a5f9fc',
    messagingSenderId: '419434734005',
    projectId: 'blood-bank-39c73',
    authDomain: 'blood-bank-39c73.firebaseapp.com',
    storageBucket: 'blood-bank-39c73.firebasestorage.app',
    measurementId: 'G-N98VYN1Y0S',
  );

}